server:
  port: 8080
  servlet:
    context-path: /api
jwt:
  secret: secretoJWT
  expiration: 3600
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations:
    - classpath:db/migration
