CREATE SEQUENCE SUPERHERO_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE SUPERHERO (
    ID INT NOT NULL DEFAULT NEXTVAL('SUPERHERO_SEQUENCE') PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ABILITY VARCHAR(255) NOT NULL,
    UNIVERSE VARCHAR(255)
);

COMMIT;