CREATE SEQUENCE USER_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
    ID INT NOT NULL DEFAULT NEXTVAL('USER_SEQUENCE') PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);

COMMIT;